/*
 * GP Practice API
 *
 * ## API for GP Practice lookups
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gprecords

type GpRecordResponse struct {

	// GMC Organisation Code
	GmcCode string `json:"gmcCode"`

	// GP Name
	Name string `json:"name"`

	// Comma separated list of address lines
	Address string `json:"address"`

	// PostCode of the GP
	PostCode string `json:"postCode"`

	// NHS code for the practice
	PracticeCode string `json:"practiceCode"`
}
