openapi: "3.0.2"
info:
  version: 1.0.0
  title: GP Practice API
  description: |
    ## API for GP Practice lookups
servers:
  - url: http://gppractice.com/api/gp
tags:
  - name: GP Practice
#security:
#  - bearerAuth: []   
paths:
  /GPRecord/:
    get:
      tags:
        - GP Practice
      summary: Get GP Practices  
      operationId: getGPRecord
      description: GP registered with the current practice 
      parameters:
        - name: version
          in: path
          description: API version
          required: true
          schema:
            type: string      
        - name: gmcCode
          in: path
          description: GMC Code for the GP
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GPRecordResponse'
        '400':
          description: Bad request errors
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: Unauthorized
        '404':
          description: GP GMC code not found

  /AllGPRecords/:
    get:
      tags:
        - GP Practice
      summary: Get All GP Practices  
      operationId: getAllGPRecords
      description:  All GPs registered with the current practice 
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GPRecordResponse'
        '400':
          description: Bad request errors
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: Unauthorized
        '404':
          description: GP GMC code not found




components:
  schemas:
    GPRecordResponse:
      type: object
      required:
        - gmcCode
        - name
        - address
        - postCode
        - practiceCode
      properties:
        gmcCode:
          type: string
          description: GMC Organisation Code
        name:
          description: GP Name
          type: string
        address:
          type: string
          description: Comma separated list of address lines
        postCode:
          type: string
          description: PostCode of the GP
        practiceCode:
          type: string
          description: NHS code for the practice

  
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT   
       
              